use_frameworks!

target 'ViewModelBindable_Example' do
  pod 'ViewModelBindable', :path => '../'

  target 'ViewModelBindable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
